### ISSUE TITLE
Issue re Ambient Light Level in Homebridge 1.3

### ISSUE THREAD

**Issue by siobhanellis** [keybuk/homebridge-sun-position#8]
With Homebridge 1.3.0 I now get the errors

This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://git.io/JtMGR for more info.

This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 120000 exceeded maximum of 100000. See https://git.io/JtMGR for more info.

**Comment by keybuk** [comment]
Thanks for the report,

These numbers aren't actually intended to be meaningful, I just picked them based on a table of average lux values for certain times of day, since otherwise the sensor wouldn't present any characteristic that the default Home app would be able to show.

I'll correct the plugin to use the correct min/max values

**Comment by keybuk** [comment]
Let me know if the patch fixes the issue

**Comment by siobhanellis** [comment]
All good. Thx

On Feb 20, 2021, at 11:31 AM, Scott James Remnant <notifications@github.com<mailto:notifications@github.com>> wrote:



Let me know if the patch fixes the issue

**Comment by keybuk** [comment]
Great, published the fixed version
